title: Arc
email: reda.agaoua@gmail.com
description: >-
  Everything PostgreSQL, and more.
baseurl: ""
url: "https://ragaoua.github.io"
#twitter_username: jekyllrb
github_username:  ragaoua

# Build settings
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
