title: Arc
email: reda.agaoua@gmail.com
description: >-
  Everything PostgreSQL, and more.
baseurl: ""
url: "https://ragaoua.github.io"
#twitter_username: jekyllrb
github_username:  ragaoua
author: Reda A.

# Build settings
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 5
paginate_path: "/posts/page:num/"
