title: Arc
email: reda.agaoua@gmail.com
description: >-
  Everything PostgreSQL, and more.
baseurl: ""
url: "https://ragaoua.github.io"
twitter_username: 
github_username:  ragaoua
author: Reda A.

plugins:
  - jekyll-paginate

theme: jekyll-theme-clean-blog

# Pagination (jekill-paginate)
paginate: 5
paginate_path: "/posts/page:num/"
