title: Arc
email: reda.agaoua@gmail.com
description:
baseurl: ""
url: "https://ragaoua.github.io"
twitter_username: 
github_username: ragaoua
author: Reda A.

plugins:
  - jekyll-paginate

theme: null

# Pagination (jekill-paginate)
paginate: 5
paginate_path: "/posts/page:num/"
